import type {Metadata} from 'next';

import React from 'react';

import RecoilRootWrapper from '../lib/recoil';
import StyledComponents from '../lib/registry';

export const metadata: Metadata = {
    title      : 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="ko">
        <RecoilRootWrapper>
            <StyledComponents>
                <body>
                    {children}
                    <div id="portal"></div>
                </body>
            </StyledComponents>
        </RecoilRootWrapper>
        </html>
    );
}
